name: Publish to JupiterOne
on: [push, pull_request]
jobs:
  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false
      matrix:
        node: [12]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install policy-builder
        run: yarn install @jupiterone/security-policy-builder
      - name: Publish to J1
        env:
          J1_ACCOUNT_ID: ${{ secrets.J1_ACCOUNT_ID }}
          J1_API_TOKEN: ${{ secrets.J1_API_TOKEN }}
        run: yarn publish:j1