on: [push]

jobs: 
  publish:
    runs-on: ubuntu-latest
    name: Publish to JupiterOne
    steps:
    - name: setup-node
      uses: actions/setup-node@v1
      with: 
        node-version: 12.x
    - name: checkout-code
      uses: actions/checkout@v2
    - name: install
      run: yarn install
    - name: publish
      env: 
        J1_ACCOUNT_ID: ${{ secrets.J1_ACCOUNT_ID }}
        J1_API_TOKEN: ${{ secrets.J1_API_TOKEN }}
      run: yarn publish:j1
      